# Generated by Django 5.2.10 on 2026-01-29 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTeamPOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_and_delivery_leads', models.JSONField(blank=True, default=dict)),
                ('functional_pocs', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_team_pods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_team_pod',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CriticalRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='critical_risks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'critical_risk',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('headquarter_location', models.CharField(blank=True, max_length=200, null=True)),
                ('csat', models.CharField(blank=True, max_length=100, null=True)),
                ('version_1_vertical', models.CharField(blank=True, max_length=200, null=True)),
                ('current_work', models.JSONField(blank=True, default=list)),
                ('service_lines', models.JSONField(blank=True, default=list)),
                ('customer_perception', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GrowthStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('growth_aspiration', models.JSONField(blank=True, default=list)),
                ('key_vectors_for_driving_growth', models.JSONField(blank=True, default=list)),
                ('improve_quality_sustainability_revenues', models.JSONField(blank=True, default=list)),
                ('potential_inorganic_opportunities', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='growth_strategies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'growth_strategy',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=list)),
                ('total_investment_value', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investment_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'investment_plan',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationalExcellence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_gp_percent', models.CharField(blank=True, max_length=50, null=True)),
                ('gp_ambition_percent', models.CharField(blank=True, max_length=50, null=True)),
                ('priority_levers_for_margin_uplift', models.JSONField(blank=True, default=list)),
                ('commercial_transformation_plan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operational_excellence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'operational_excellence',
                'ordering': ['-updated_at'],
            },
        ),
    
        migrations.CreateModel(
            name='ServiceLineGrowth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_transformation', models.JSONField(blank=True, default=dict)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('ai', models.JSONField(blank=True, default=dict)),
                ('srg_managed_services', models.JSONField(blank=True, default=dict)),
                ('ea', models.JSONField(blank=True, default=dict)),
                ('strategy_design_and_change', models.JSONField(blank=True, default=dict)),
                ('sam_and_licensing', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_line_growths', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'service_line_growth',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='StrategicPartnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=200)),
                ('internal_poc', models.CharField(blank=True, max_length=200, null=True)),
                ('partner_type', models.CharField(blank=True, max_length=200, null=True)),
                ('sell_with_revenue_fy25_actuals_forecast', models.CharField(blank=True, max_length=100, null=True)),
                ('sell_with_revenue_fy26_target', models.CharField(blank=True, max_length=100, null=True)),
                ('key_engagements', models.TextField(blank=True, null=True)),
                ('support_needed', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strategic_partnerships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
