# Generated by Django 5.2.10 on 2026-01-21 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('headquarter_location', models.CharField(blank=True, max_length=200, null=True)),
                ('csat', models.CharField(blank=True, max_length=100, null=True)),
                ('version_1_vertical', models.CharField(blank=True, max_length=200, null=True)),
                ('current_work', models.JSONField(blank=True, default=list)),
                ('service_lines', models.JSONField(blank=True, default=list)),
                ('customer_perception', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GrowthStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('growth_aspiration', models.JSONField(blank=True, default=list)),
                ('key_vectors_for_driving_growth', models.JSONField(blank=True, default=list)),
                ('improve_quality_sustainability_revenues', models.JSONField(blank=True, default=list)),
                ('potential_inorganic_opportunities', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='growth_strategies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'growth_strategy',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='StrategicPartnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=200)),
                ('internal_poc', models.CharField(blank=True, max_length=200, null=True)),
                ('partner_type', models.CharField(blank=True, max_length=200, null=True)),
                ('sell_with_revenue_fy25_actuals_forecast', models.CharField(blank=True, max_length=100, null=True)),
                ('sell_with_revenue_fy26_target', models.CharField(blank=True, max_length=100, null=True)),
                ('key_engagements', models.TextField(blank=True, null=True)),
                ('support_needed', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strategic_partnerships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
