# Generated by Django 5.2.10 on 2026-01-21 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTeamPOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_and_delivery_leads', models.JSONField(blank=True, default=dict)),
                ('functional_pocs', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_team_pods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_team_pod',
                'ordering': ['-updated_at'],
            },
        ),
    ]
