# Generated by Django 5.2.10 on 2026-01-21 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_accountteampod'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceLineGrowth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_transformation', models.JSONField(blank=True, default=dict)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('ai', models.JSONField(blank=True, default=dict)),
                ('srg_managed_services', models.JSONField(blank=True, default=dict)),
                ('ea', models.JSONField(blank=True, default=dict)),
                ('strategy_design_and_change', models.JSONField(blank=True, default=dict)),
                ('sam_and_licensing', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_line_growths', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'service_line_growth',
                'ordering': ['-updated_at'],
            },
        ),
    ]
