# Generated by Django 5.2.10 on 2026-01-21 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_investmentplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalExcellence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_gp_percent', models.CharField(blank=True, max_length=50, null=True)),
                ('gp_ambition_percent', models.CharField(blank=True, max_length=50, null=True)),
                ('priority_levers_for_margin_uplift', models.JSONField(blank=True, default=list)),
                ('commercial_transformation_plan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operational_excellence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'operational_excellence',
                'ordering': ['-updated_at'],
            },
        ),
    ]
